# Generated by Django 6.0.1 on 2026-01-27 23:26

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('BILLING', 'Billing'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], max_length=20), blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['assigned_to', 'status', '-created_at'], name='tickets_tic_assigne_385617_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='tickets_tic_tags_d75f6b_gin')],
            },
        ),
    ]
